### ISSUE TITLE
train_model 'cabasc' can't run

### ISSUE THREAD

**Issue by linwangolo** [AlexYangLi/ABSA_Keras#4]
Hi,

I ran train.py of the previous commit, but only 'cabasc' got an error as follows:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Matrix size-incompatible: In[0]: [2336,300], In[1]: [1324,1324]
         [[{{node model_1/content_attention_1/MatMul_1}}]]
         [[{{node metrics/acc/Mean}}]]`

At that time, the code toggle comments on most of train_model(...) and just ran fixed word/aspect embedding part, i.e.

    config.word_embed_trainable = False
    config.aspect_embed_trainable = False
    train_model('laptop/term', 'laptop', 'word', 'td_lstm')
    train_model('laptop/term', 'laptop', 'word', 'tc_lstm')
    train_model('laptop/term', 'laptop', 'word', 'ae_lstm')
    train_model('laptop/term', 'laptop', 'word', 'at_lstm')
    train_model('laptop/term', 'laptop', 'word', 'atae_lstm')
    train_model('laptop/term', 'laptop', 'word', 'memnet')
    train_model('laptop/term', 'laptop', 'word', 'ram')
    train_model('laptop/term', 'laptop', 'word', 'ian')
    # train_model('laptop/term', 'laptop', 'word', 'cabasc')

    

Only 'cabasc' was toggled comment and did not plot on the results of combining ELMo Embedding as well.

So I guess that 'cabasc' can not run in this condition?

**Comment by AlexYangLi** [comment]
Hi, this error is mainly because the size of aspecte embedding doesn't equal with that of text embedding when using elmo as input. I have already fixed that in the latest commit.

**Comment by linwangolo** [comment]
It's solved.
Thanks a lot.
